# Generated by Django 4.2.8 on 2024-03-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.IntegerField()),
                ('name', models.CharField(max_length=70)),
                ('is_deleted', models.BooleanField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
