# Generated by Django 4.2.8 on 2024-03-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_created_at_employee_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='deleted_by',
            field=models.IntegerField(null=True),
        ),
    ]
