# Generated by Django 4.2.8 on 2024-03-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_deleted_at_employee_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='restored_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='restored_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
