# Generated by Django 4.2.8 on 2024-03-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_restored_at_employee_restored_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='restored_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
