# Generated by Django 4.2.8 on 2024-01-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('marks_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Maths', models.FloatField()),
                ('Physics', models.FloatField()),
                ('Chemistry', models.FloatField()),
                ('Computer', models.FloatField()),
                ('English', models.FloatField()),
                ('Hindi', models.FloatField()),
                ('Total_marks_per_subject', models.FloatField()),
                ('Total_marks_obtained', models.FloatField()),
                ('Percentage', models.FloatField()),
                ('pass_fail', models.BooleanField()),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
