# Generated by Django 4.2.8 on 2024-03-16 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudo_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
