# Generated by Django 4.2.8 on 2024-03-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sudo_app', '0002_delete_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=70)),
            ],
        ),
    ]
