# Generated by Django 4.2.8 on 2024-03-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudo_app', '0004_employeeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeid',
            name='employeeID',
            field=models.CharField(max_length=10),
        ),
    ]
