# Generated by Django 4.2.8 on 2024-03-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudo_app', '0007_employee_profile_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedSubordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('hr_id', models.IntegerField()),
            ],
        ),
    ]
