# Generated by Django 4.2.8 on 2024-03-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudo_app', '0009_rename_assignedsubordinate_assignedsubordinatehr'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignSSubordinateToManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.IntegerField()),
                ('hr_id', models.IntegerField()),
            ],
        ),
    ]
