# Generated by Django 4.2.8 on 2024-03-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudo_app', '0011_employee_profile_assigned_subordinate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedSubordinateHr',
        ),
        migrations.DeleteModel(
            name='AssignSSubordinateToManager',
        ),
    ]
