# Generated by Django 4.2.8 on 2024-03-21 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sudo_app', '0013_alter_employee_profile_assigned_subordinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_profile',
            name='created_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_employee_profiles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
