# Generated by Django 4.2.8 on 2024-03-21 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sudo_app', '0014_employee_profile_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_employee_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
