# Generated by Django 4.2.8 on 2024-03-24 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sudo_app', '0015_alter_employee_profile_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_profile',
            name='assigned_users_by_admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users_by_admin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
