# Generated by Django 4.2.8 on 2024-03-24 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudo_app', '0016_employee_profile_assigned_users_by_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_profile',
            name='assigned_users_by_admin',
        ),
    ]
