# Generated by Django 4.2.8 on 2024-03-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudo_app', '0018_employee_profile_assigned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_profile',
            name='assigned_by',
        ),
    ]
