# Generated by Django 4.2.8 on 2024-03-12 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_hr_model_created_at_hr_model_created_by_and_more'),
        ('manager', '0002_rename_managerid_managermodel_managerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='managermodel',
            name='hr_under_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_app.hr_model'),
        ),
    ]
