# Generated by Django 4.2.8 on 2024-03-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_hr_model_created_at_hr_model_created_by_and_more'),
        ('manager', '0003_managermodel_hr_under_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managermodel',
            name='hr_under_manager',
        ),
        migrations.AddField(
            model_name='managermodel',
            name='hr_under_manager',
            field=models.ManyToManyField(to='hr_app.hr_model'),
        ),
    ]
