# Generated by Django 4.2.8 on 2024-03-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hr_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HrID', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
