# Generated by Django 4.2.8 on 2024-03-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_model',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
    ]
