# Generated by Django 4.2.8 on 2024-03-09 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hr_model',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_hr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hr_model',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hr_model',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_hr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hr_model',
            name='restored_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hr_model',
            name='restored_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restored_hr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hr_model',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hr_model',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hr_model',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_hr', to=settings.AUTH_USER_MODEL),
        ),
    ]
