# Generated by Django 4.2.8 on 2024-03-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_created_by_alter_employee_deleted_by_and_more'),
        ('hr_app', '0002_hr_model_created_at_hr_model_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_model',
            name='employees_under_hr',
            field=models.ManyToManyField(to='employee.employee'),
        ),
    ]
