# Generated by Django 4.2.8 on 2024-03-27 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_app', '0003_hr_model_employees_under_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_model',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
