# Generated by Django 4.2.8 on 2024-03-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0004_hr_model_assigned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr_model',
            name='assigned_by',
        ),
    ]
