# Generated by Django 4.2.8 on 2024-02-02 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0004_remove_student_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(max_length=70)),
                ('date', models.DateField(verbose_name='Date of attendance')),
                ('no_of_days_present', models.IntegerField(verbose_name='Number of Days Present')),
                ('student_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
