# Generated by Django 4.2.8 on 2024-01-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(blank=True, max_length=70)),
                ('Father_Name', models.CharField(blank=True, max_length=70)),
                ('roll_no', models.IntegerField(blank=True)),
                ('mobile', models.BigIntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
