# Generated by Django 4.2.8 on 2024-01-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Father_Name',
            field=models.CharField(blank=True, max_length=70, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_Name',
            field=models.CharField(blank=True, max_length=70, verbose_name="Student's name"),
        ),
    ]
