# Generated by Django 4.2.8 on 2024-02-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_date_created_student_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(choices=[('Lucknow', 'Lucknow'), ('Banaras', 'Banaras'), ('Kanpur', 'Kanpur'), ('Hardoi', 'Hardoi'), ('Allahabad', 'Allahabad'), ('Bareilly', 'Bareilly')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
